openapi: 3.0.0
servers:
# Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ivanalfonso88/Convenios/1.0.0
  - url: 'https://petstore.swagger.io/v2'
info:
  description: Este es el API de Convenios para Toures Balon
  version: "1.0.0"
  title: Convenios API
  contact:
    email: touresbalon@archetype.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: Convenios
    description: Operaciones de consulta, creacion, actualizacion y eliminacion de convenios
paths:
  /convenios:
    get:
      tags:
        - Convenios
      summary: Consulta la información de los convenios basado en parámetros de búsqueda
      operationId: ConveniosGETAll
      description: |
        Consulta la información de los convenios basado en parámetros de búsqueda
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: El número de convenios a retornar
        - in: query
          name: nombre
          schema:
            type: integer
          description: Nombre para consultar convenios
        - in: query
          name: estado
          schema:
            type: string
            enum:
              - ACTIVO
              - INACTIVO
          description: Estado del convenio.
      responses:
        '200':
          description: Consulta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConveniosGETAllRs'
                example: 
                  convenios: 
                    - convenio:
                      nombreProveedor: 'Nombre'
                      identificacion: '1234567'
                      tipoConvenio: 'HOSPEDAJE'
                      fechaVigencia: '01/01/2020'
                      correo: 'optimusPrime@toures.com'
                      pais:
                        codigo: 'COL'
                      ciudad:
                          codigo: 'BOG'
        '400':
          description: Parametro invalido
        '500':
          description: Error del sistema
        '401':
          description: No autorizado
    post:
      tags:
        - Convenios
      summary: Registrar un nuevo convenio
      operationId: ConveniosPST
      description: Crea el convenio de acuerdo con los parámetros recibidos.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConveniosPSTRq'
            example: 
              convenio:
                nombreProveedor: 'TOURING'
                identificacion: '123456'
                tipoConvenio: 'HOSPEDAJE'
                fechaVigencia: 'optimusPrime@ffdd.com'
                pais:
                    codigo: 'COL'
                ciudad:
                    codigo: 'BOG'
                 
        description: Convenio a registrar
      responses:
        '201':
          description: Convenio registrado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConveniosPSTRs'
              example: 
                convenio:
                  identificacion: '12345'
        '400':
          description: 'Parametro Invalido'
        '409':
          description: Convenio ya existe  
        '500':
          description: Error del sistema           
  /convenios/{identificacion}:
    get:
      tags:
        - Convenios
      summary: Consulta al información de un convenio por su id
      operationId: ConveniosGETById
      description: |
        Consulta al información de un convenio por su id
      parameters:
        - name: identificacion
          in: path
          description: Identificación del convenio
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Consulta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConveniosGETByIdRs'
                example: 
                  convenio:
                    nombreProveedor: 'Nombre'
                    identificacion: '123456'
                    tipoConvenio: 'TRANSPORTE'
                    fechaVigencia: '01/01/2020'
                    correo: 'optimusPrime@toures.com'
                    pais:
                      codigo: 'COL'
                    ciudad:
                      codigo: 'BOG'
        '400':
          description: Parametro invalido
        '500':
          description: Error del sistema
        '401':
          description: No autorizado
    patch:
      tags:
        - Convenios
      summary: Actualizar información del convenio
      operationId: ConveniosPCT
      description: Actualiza el convenio de acuerdo con los parámetros recibidos.
      parameters:
        - name: identificacion
          in: path
          description: identificacion del convenio
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConveniosPCTRq'
            example: 
              convenio:
                nombreProveedor: 'touring'
                tipoConvenio: 'HOPEDAJE'
                correo: 'jj@toures.com'
        description: Convenio a actualizar
      responses:
        '201':
          description: Convenio actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConveniosPCTRs'
              example: 
                convenio:
                  identificacion: '12345'
        '400':
          description: 'Parametro Invalido'
        '500':
          description: Error del sistema
    delete:
      tags:
        - Convenios
      summary: Borrar el convenio por su identificacion
      operationId: ConveniosDEL
      description: Borra el convenio de acuerdo a la identificacion recibida.
      parameters:
        - name: identificacion
          in: path
          description: identificacion del convenio
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Convenio eliminado exitosamente
        '400':
          description: 'Parametro Invalido'
        '500':
          description: Error del sistema
    
components:
  schemas:
    ConveniosGETAllRs:
      description: Respuesta a consulta de todos los convenios
      type: object
      required:
        - convenios
      properties:
        convenios:
          type: array
          items:
            allOf:
              - $ref: 'https://api.swaggerhub.com/domains/ivanalfonso88/DominioConvenios/1.0.0#/components/schemas/Convenio'
            properties:
              direcciones:
                required: 
                  - direccion  
            required: 
              - identificacion
    ConveniosPCTRq:
      description: Peticion de actualizacion de un convenio
      type: object
      required:
        - convenio
      properties:
        convenio:
          allOf:
            - $ref: 'https://api.swaggerhub.com/domains/ivanalfonso88/DominioConvenios/1.0.0#/components/schemas/Convenio'
            - type: object
          required: 
            - nombreProveedor
            - tipoConvenio
            - fechaVigencia
            - correo
            - pais
            - ciudad
    ConveniosPCTRs:
      description: Respuesta a la actualizacion de un convenio
      type: object
      required:
        - convenio
      properties:
        convenio:
          allOf:
            - $ref: 'https://api.swaggerhub.com/domains/ivanalfonso88/DominioConvenios/1.0.0#/components/schemas/Convenio'
            - type: object
          required: 
            - id
    ConveniosGETByIdRs:
      description: Respuesta a la consulta de un convenio por Id
      type: object
      required:
        - convenio
      properties:
        convenio:
          allOf:
            - $ref: 'https://api.swaggerhub.com/domains/ivanalfonso88/DominioConvenios/1.0.0#/components/schemas/Convenio'
            - type: object
          required: 
            - nombreProveedor
            - identificacion
            - tipoConvenio
            - fechaVigencia
            - correo
            - pais
            - ciudad
    ConveniosPSTRq:
      description: Peticion de creacion de un convenio
      type: object
      required:
        - convenio
      properties:
        convenio:
          allOf:
            - $ref: 'https://api.swaggerhub.com/domains/ivanalfonso88/DominioConvenios/1.0.0#/components/schemas/Convenio'
            - type: object
    ConveniosPSTRs:
      description: Respuesta a la creacion de un convenio
      type: object
      required:
        - convenio
      properties:
        convenio:
          allOf:
            - $ref: 'https://api.swaggerhub.com/domains/ivanalfonso88/DominioConvenios/1.0.0#/components/schemas/Convenio'
            - type: object
          required: 
            - nombreProveedor
            - identificacion